### ISSUE TITLE
bypass killaura easy with addon

### ISSUE THREAD

**Issue by Marcobagastruz** [konsolas/AAC-Issues#1508]
### Core information
**Server version**:  1.8.8 paperspigot

**AAC version**:  3.5.0 b1

**ProtocolLib version**:  #403

**Plugin list**: no plugins that edit hits or anithing on pvp.

### Special environment information
**ViaVersion version**: no viaversion

**ProtocolSupport version**: no

**ViaBackwards version**: no

**BungeeCord plugins**: serverlistplus,skinrestorer

### Configuration
```
killaura:
   # Do you want to enable the killaura check?
   enabled: true

   # Should AAC cancel impossible hits?
   cancel_hit: true

   # How many violations before hits start being cancelled?
   min_vl: 49

   # How much should AAC increase the violation level for each detection method?
   modules:
      natural: 5
      round: 10
      split: 5
      sporadic: 6
      stable: 6
      switch: 4
      angle: 2
      click: 3
      miss: 3
      tick: 9
      yaw: 6
      normal: 2
      look: 11
      timing: 6
      accel: 7
      accuracy: 20
      pattern: 10

   # Map of violation levels to commands:
   thresholds:
      30: "aacstaffnotify {player} in {world} might be using killaura (ping = {ping}, tps = {tps})"
      75:
       - "aacstaffnotify {player} kicked for killaura hacking (Killaura - Normal) (ping = {ping}, tps = {tps})"
       - "tempban {player} 10d Killaura"
.
```
