### ISSUE TITLE
1.13.2 Tab Complete Permissions Issue.

### ISSUE THREAD

**Issue by LogGits** [konsolas/AAC-Issues#1553]
### Issue description
Players without permission for commands can still see them in tabcomplete on 1.13. This is because the plugin.yml would be setup incorrectly. To fix this, a permissions setup like this would prevent a player from seeing a tabcomplete for an admin command that they don't have perms for:
```yaml
commands:
  start:
    description: hub of important commands.
    aliases: info
    permission: test.start

permissions:
  test.start:
    description: give access to /start
    default: true
```

### Core information
**Server version**: 1.13.2

**AAC version**: 3.6.4
