### ISSUE TITLE
Threshold commands not executing from top to bottom, resulting in status command outputting "player not found"

### ISSUE THREAD

**Issue by ChiboYen** [konsolas/AAC-Issues#2050]
### Issue description
```
[23:21:55 INFO]: [AAC5] actions.movement: aac reset ChiboYen
[23:21:55 INFO]: [AAC5] actions.movement: kick ChiboYen actions.movement
[23:21:55 INFO]: No player was found
```
AAC attempts to reset the data of the kicked player and kick the player FIRST and then it runs the status command, this is, however, counterproductive as I would like to have a log of the status of the player before they are kicked.

Here is my config:
```
  movement:
    features:
      - aac_move_*
      - aac_delays_sneak
      - aac_delays_release
    thresholds:
      190:
        - "aac status %player_name%"
        - "aac reset %player_name%"
        - "kick %player_name% Please refrain from using hacks on this server [M]"
```
It would be nice if the actions of the threshold at the configured VL would execute in order, such as status -> reset -> kick, but in its current state (pre23), the observed behavior is kick -> reset -> status (no player found).

### Core information
**Server version**: 1.16.4

**AAC version**: AAC5 Pre23

**ProtocolLib version**: Latest dev build, 6.4.0 snapshot

**Plugin list**: N/A

### Special environment information
**ViaVersion version**:  N/A

**ProtocolSupport version**:  N/A

**ViaBackwards version**:  N/A

**BungeeCord plugins**:  N/A

### Configuration
Default config movement threshold with a lower VL level (190), config above.
