### ISSUE TITLE
AAC VL not being added under high frequency API calls

### ISSUE THREAD

**Issue by GitGoppy** [konsolas/AAC-Issues#2171]
### Issue description

So I talked to Photon about AACadditionpro, there seemed to be a bug with skinblinker check not getting all VLs passed on AAC as it should.
We confirmed that this is isolated to this check and AAC is getting correct API calls.
AAC seems to not add violations properly when adding violations at high frequency.

### Core information
**Server version**: paper1-16-5 #468

**AAC version**: 5.0.11

**ProtocolLib version**: ProtocolLib v4.6.0-SNAPSHOT-b492

### Configuration
```yaml
  skinblinker:
    delay: 1.0
    features:
      - aacadditionpro_skinblinker
    thresholds:
      250:
        - "aac status %player_name%"
        - "aac reset %player_name%"
        - "kick %player_name% Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host."
```
