### ISSUE TITLE
HElp me to configure AAC move

### ISSUE THREAD

**Issue by SharkblackFr** [konsolas/AAC-Issues#2172]
Hi,
I have a problem when a player walk on the stairs is detected as "SPECTATE"
here is my config:

```yaml
 #Move controls player movement.
 move:
   enabled: true
   #Should AAC check players asynchronously?
   #Default: false
   async: false
   #What's the maximum amount that a single violation should be able to add to a player's VL?
   #Default: 500
   max_vl_increment: 430
   #How many simulations should AAC carry forward from the previous movement?
   #Default: 3
   simulation_limit: 3
   #Control how AAC checks movements in general:
   normal:
     #How lenient should AAC be when checking?
     #Default: 0.001
     tolerance: 0.024
     #How lenient should AAC be when a player is being pushed by another entity? 
     #Default: 0.1
     bumping: 0.11
     #How much should a move violation of this type contribute to a player's overall VL?
     #Default: 1.0
     weight: 1.7
   #Control how AAC checks movements in water:
   water:
     #How lenient should AAC be when checking?
     #Default: 0.001
     tolerance: 0.017
     #How fast should players be able to move with riptide?
     #Default: 4.2
     riptide_speed: 4.2
     #How much should AAC allow flowing water to accelerate a player?
     #Default: 0.1
     flowing: 0.19
     #How much should AAC allow bubble columns to accelerate a player?
     #Default: 1.8
     bubble_column: 1.8
     #How lenient should AAC be when a player is around boats?
     #Default: 0.6
     boat: 0.6
     #How much should a move violation of this type contribute to a player's overall VL?
     #Default: 1.0
     weight: 1.3
   #Control how AAC checks movements while using the elytra:
   elytra:
     #How lenient should AAC be when checking?
     #Default: 0.001
     tolerance: 0.001
     #How quickly should players be able to travel when rocket boosting with an elytra?
     #Default: 2.0
     rocket_speed: 2.0
     #How much should a move violation of this type contribute to a player's overall VL?
     #Default: 0.6
     weight: 0.7
   #Control how AAC checks movements when on a vehicle:
   vehicle:
     #How lenient should AAC be when checking?
     #Default: 0.001
     tolerance: 0.001
     #How much should a move violation of this type contribute to a player's overall VL?
     #Default: 0.2
     weight: 0.3
   #Control how AAC checks skipped movements:
   skipped:
     #How lenient should AAC be when checking?
     #Default: 0.03
     tolerance: 0.037
     #How long must a movement be for AAC to use timer checking?
     #Default: 0.1
     min_length: 0.1
   #Control how AAC checks movement when velocity is applied:
   velocity:
     #Should AAC check for anti-velocity?
     #Default: true
     enabled: true
     #How long should AAC wait for a player to send the correct velocity?
     #Default: 12
     wait_ticks: 12
     #Should AAC check players who remain entirely stationary?
     #Default: true
     check_stationary: true
     #How much should AAC add to a player's VL if they ignore velocity?
     #Default: 100
     vl_increment: 180
   #Control how the violation level decays over time:
   decay:
     #Default: 1
     interval: 2
     #Default: 20
     delay: 20
     #Default: 1
     amount: 1
   #Control how AAC mitigates a cheater's actions:
   mitigation:
     #Default: true
     enabled: true
     #Default: 250
     min_vl: 370
```

thanks for yout help
