### ISSUE TITLE
Suggestion: PAPI support in config

### ISSUE THREAD

**Issue by kacperleague9** [konsolas/AAC-Issues#2247]
My suggestion is to add support for PlaceholderAPI in AAC configuration, example (MOST LIKELY IT WONT EVEN WORK ITS JUST AN EXAMPLE):
```
  interact:
    enabled: true

    # AAC will accept interactions as long as the player is aiming close to their target block
    # This is the max angle that AAC will accept (in radians)
    max_angle_diff: 1.0

    # AAC will not check interactions with these materials
    exempt: []

    # interact.vl increases by 1 for each invalid interaction that is detected
    vl:
      mitigate: true
      threshold: %player_ping%
      max: 1.0
      decay: 0.01
```
