### ISSUE TITLE
Combat Upgrade (Weight Hits)

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#454]
My request could be a godsend for configuration and will help deal with some issues in combat detection.

Today's combat checks (KillAura & Hitbox) tend to be too touchy to keep strict but seemingly worthless when you reduce sensitivity to stop false detections from mob grinders and/or spam clicking a bunch of mobs. Both of which are exacerbated with a little lag.

My request is that HB and KA gain a configuration option to modify the violation weight per hit based on the target being a human or non-human. As a result, hackers attacking players will gain VL quicker since we no longer need to devalue the check because of mob detection issues. This will also give owners the option to ignore mobs entirely if they so choose (about 15 people have asked me if this is possible)

```
hitbox:
   max_dist: 2.6

   # Violation accumulated for illegal hits on human entities
   player_vl: 3

   # Violation accumulated for illegal hits on non-human entities
   mob_vl: 1

   # Minimum number of violations before AAC starts cancelling hits
   min_vl: 6
```

```
killaura:
   # How long should the check last?
   duration: 20

   # Violation accumulated for illegal hits on human entities
   player_vl: 4

   # Violation accumulated for illegal hits on non-human entities
   mob_vl: 2

   # How far off should a player be able to look to allow the hit
   max_diff: 0.11
```

For Killaura, these would replace the `weight` option.
