### ISSUE TITLE
"Move" present in violation log with all move-checks disabled

### ISSUE THREAD

**Issue by freak-dk** [konsolas/AAC-Issues#797]
**Issue**
I have every move-related check disabled in my config, yet I still see the move-check triggered in violation log?
As seen here: http://prntscr.com/fr2pkh
Move checks disabled: http://prntscr.com/fr2rus

I am just wondering if this is intentional behaviour?

**Server version**: 
Newest 1.8.8 PaperSpigot build:
http://prntscr.com/fr2qdz

**AAC version**:  3.2.1-b1

**ProtocolLib version**: 4.2.0

### Special environment information
Insert 'none' if you don't use it

**ViaVersion version**: 1.1.1-Snapshot

**ProtocolSupport version**: none

**ViaBackwards version**: none

**BungeeCord plugins**: none

**Comment by CeIebrimbor** [comment]
Make sure you disable the `move` check manually in the AAC config. This one of the final checks in the config.

**Comment by freak-dk** [comment]
@CeIebrimbor 
Exactly what should I set the values to, to disable completely?
Currently default; 

move:
   # Maximum lagspike size to compensate for (ticks)
   min_balance: -20

   # Maximum extra packets before cancelling (and causing movement violations)
   cancel_threshold: 5

   # Default balance when networking heuristics determine that the connection is normal
   reset_level: -1

   # Maximum packet overload level to hold a player at.
   balance_cap: 10

**Comment by CeIebrimbor** [comment]
If you have the latest config (if those are your only move configuration options, you do not), then you would have an `enabled` option. Make sure you update your config when updates have config changes.

**Comment by CeIebrimbor** [comment]
For the record, this is the current default section for the move check

```
# Parameters for AAC's packet level movement check system. It is required for all non-combat checks
# Monitors movement rate and illegal movement positions.
move:
   # This must be enabled to use any movement check in AAC, and is also required for some world and combat checks.
   # Do not disable unless you are exclusively using combat checks in AAC.
   enabled: true

   # Maximum lagspike size to compensate for (ticks)
   min_balance: -50

   # Maximum extra packets before cancelling (and causing movement violations)
   cancel_threshold: 5

   # Default balance when networking heuristics determine that the connection is normal
   reset_level: -1

   # Maximum packet overload level to hold a player at.
   balance_cap: 10

   # At what tick interval should AAC reduce 1 VL from the player?
   decay: 25

   # Map of violation levels to commands
   thresholds:
      200: "aacstaffnotify {player} in {world} is sending unusual movement information (ping = {ping}, tps = {tps})"
      500: "aackick {player} Sending unusual movement packets"
```
