### ISSUE TITLE
Interact check does not work properly for non-full blocks -> Expanded scaffold etc. possible

### ISSUE THREAD

**Issue by Nvaros** [konsolas/AAC-Issues#809]
Normally, the interact check prevents placing blocks illegal so it blocks expanded Scaffold.
But for any non-full block such as fences, iron bars, daylight detector, stairs and slabs, it doesn't really work.
If you stay on a solid block and toggle expanded scaffoldwalk, it flags like it should, but if you place two of those blocks ahead and toggle it again (from the solid block, as doing it directly on the non-full block flags too), you can use it freely without any flags except you walk sidewards. 
Of course, any ghosthand and fucker goes through those blocks too.

I can't show any video proof, but you can test it on any test server with /give or on real servers like Twerion (they have the latest version of AAC and their Interact check is enabled) on skywars.

For Bedwars, this shouldn't be a problem as most servers used sandstone or stained clay, but it is a critical "bypass" for skywars because on almost any server you can get glass blocks and wood (crafting) (e. g. Twerion, Gomme, ...)

**Comment by CeIebrimbor** [comment]
Did you test just on Twerion?

If so, for the record, their Interact settings are:
```
interact:
   enabled: true
#
# Enable/disable individual interaction detection types.
# All Default(true)
   cancel_liquids: true
   cancel_ghost_block: true
   cancel_dead: true
   cancel_item_attack: true
   cancel_ghost_attack: true
#
# Violations before AAC starts canceling interact when detecting ghosthand || 0 = Cancel 1st/all detections (only recommended for break)
# Default(5)
   cancel_vl_interact: 6
# Default(5)
   cancel_vl_place: 8
# Default(0)
   cancel_vl_break: 0
```

They do not use AACaddition to my knowledge. I will ask the owner.
