### ISSUE TITLE
Spectating Player + Void = Move

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/AAC-Issues#838]
### Issue description
Replicate: Gamemode 3 and spectate a player who jumps in the void.

Watch last 15 seconds of video:
https://www.youtube.com/watch?v=XgQvt2uD8Vk&feature=youtu.be

### Core information
**Server version**: 1.8.8

**AAC version**: 3.2.2

**ProtocolLib version**: 4.2.0

**Plugin list**: Looks like a vanilla issue

### Special environment information
**ViaVersion version**: Latest

### Configuration
```
move:
   min_balance: -90
   cancel_threshold: 5
   reset_level: -1
   balance_cap: 10
   decay: 25
```
Default kick thresholds (don't think it matters even if it was kicking at 500 or 5000)
