### ISSUE TITLE
1.12 clients on 1.8 server will pass through SOIL

### ISSUE THREAD

**Issue by MineTheCube** [konsolas/AAC-Issues#906]
### Issue description
Probably since `3.3.1` or `3.3.1-b1`, players in recent versions (especially 1.12) will fall through SOIL blocks on 1.8.8 servers. Then they are stuck and kicked for fly when they try to move/jump. I can add more information if you need to, but this is relatively easy to reproduce.

### Core information
**Server version**: spigot 1.8.8

**AAC version**: 3.3.1-b1

**ProtocolLib version**: 4.3.0

**Plugin list**: _ask if needed_

### Special environment information
**ViaVersion version**: 1.2.1

**ProtocolSupport version**: no

**ViaBackwards version**: no

**BungeeCord plugins**: _ask if needed_

### Configuration
```
heuristics:
   min_confidence: 85
nofall:
   deal_damage: false
fly:
   abilities: false
badpackets:
   max_moves: 20
```
